{
 "title": "MongoDB Instances Overview",
 "tags": [
  "MongoDB",
  "Percona",
  "Services"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_up{environment=~\"$environment\"},cluster)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\"}, node_name)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mongodb_up{environment=~\"$environment\",cluster=~\"$cluster\",node_name=~\"$node_name\"}, service_name)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
   }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(mongodb_up{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Min MongoDB Uptime",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 3 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_instance_uptime_seconds{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Total Used Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 9, "y": 3 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mongodb_memory{service_name=~\"$service_name\",type=~\"resident|virtual\"})"
    }
   ]
  },
  {
   "title": "Total Used Mapped Memory",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 14, "y": 3 },
   "format": "bits",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mongodb_memory{service_name=~\"$service_name\",type=~\"mapped|mapped_with_journal\"})"
    }
   ]
  },
  {
   "title": "Total Current QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 19, "y": 3 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]))"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Top Connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"} or\nmongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"} or\nmongodb_connections{service_name=~\"$service_name\", state=\"current\"})"
    }
   ]
  },
  {
   "title": "Top Opened Cursors",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 6 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Min QPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 6 },
   "format": "ops",
   "valueName": "min",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or\nirate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max Latency",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 6 },
   "format": "µs",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[5m]) > 0)\n)"
    }
   ]
  },
  {
   "title": "Connections Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Connections",
     "type": "graph",
     "description": "TCP connections (Incoming) in mongod processes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Current Connections",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongod_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_mongos_connections{service_name=~\"$service_name\", state=\"current\"}[5m]) or\nmax_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[$interval]) or max_over_time(mongodb_connections{service_name=~\"$service_name\", state=\"current\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cursors Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Total Cursors",
     "type": "graph",
     "description": "Open cursors count",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"total\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"total\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"total\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"total\"})))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"total\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"total\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"total\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"total\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Total Cursors",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "avg by (service_name) (mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"total\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"total\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"total\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"total\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Pinned Cursors ",
     "type": "graph",
     "description": "Open cursors that are in pinned state.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"pinned\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"pinned\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"pinned\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"pinned\"})))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"pinned\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"pinned\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"pinned\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"pinned\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Pinned Cursors",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "avg by (service_name) (mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"pinned\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"pinned\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"pinned\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"pinned\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 noTimeout Cursors",
     "type": "graph",
     "description": "noTimeout cursors currently open",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"noTimeout\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"noTimeout\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"noTimeout\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"noTimeout\"})))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"noTimeout\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"noTimeout\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"noTimeout\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"noTimeout\"})",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "noTimeout Cursors",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "avg by (service_name) (mongodb_mongod_metrics_cursor_open{service_name=~\"$service_name\", state=\"noTimeout\"} or\nmongodb_mongod_cursors{service_name=~\"$service_name\", state=\"noTimeout\"} or\nmongodb_mongos_metrics_cursor_open{service_name=~\"$service_name\", state=\"noTimeout\"} or \nmongodb_mongos_cursors{service_name=~\"$service_name\", state=\"noTimeout\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Latency Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Command Latency",
     "type": "graph",
     "description": "Average latency of (other) command operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[5m]) > 0)\n)))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[5m]) > 0)\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Command Latency",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"command\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"command\"}[5m]) > 0))\n",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Read Latency",
     "type": "graph",
     "description": "Average latency of read operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"read\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"read\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"read\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"read\"}[5m]) > 0)\n)))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"read\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"read\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"read\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"read\"}[5m]) > 0)\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Read Latency",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"read\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"read\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"read\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"read\"}[5m]) > 0))\n",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Write Latency",
     "type": "graph",
     "description": "Average latency of write operations",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "µs" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"write\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"write\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"write\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"write\"}[5m]) > 0)\n)))",
       "legendFormat": "{{service_name}} "
      },
      {
       "expr": "avg(rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"write\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"write\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"write\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"write\"}[5m]) > 0)\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Write Latency",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"write\"}[$interval]) / \n(rate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"write\"}[$interval]) > 0) or\nirate(mongodb_mongod_op_latencies_latency_total{service_name=~\"$service_name\",type=\"write\"}[5m]) / \n(irate(mongodb_mongod_op_latencies_ops_total{service_name=~\"$service_name\",type=\"write\"}[5m]) > 0))\n",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Min Index Scanned Ratio",
   "type": "singlestat",
   "description": "Ratio of index entries scanned / number of documents returned",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 12 },
   "format": "ops",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m]))\n)"
    }
   ]
  },
  {
   "title": "Max Index Scanned Ratio",
   "type": "singlestat",
   "description": "Ratio of number of documents returned / index entries scanned",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 12 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m]))\n)"
    }
   ]
  },
  {
   "title": "Min Document Scanned Ratio",
   "type": "singlestat",
   "description": "Ratio of index entries scanned compared divided by sum of index entries scanned plus whole documents scanned.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 12 },
   "format": "ops",
   "valueName": "min",
   "targets": [
    {
     "expr": "min(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max Document Scanned Ratio",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 12 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "max(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m]))"
    }
   ]
  },
  {
   "title": "Query Efficiency Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Index Scan Ratios",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m]))\n)))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m]))\n)",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Index Scan Ratios",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[$interval]) / ignoring(state) \nrate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])\nor\n(irate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned\"}[5m]) / ignoring(state) \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Document Scan Ratios",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Scan Ratios",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[$interval])/ ignoring(state)\nrate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[$interval])\nor\nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\", state=\"returned\"}[5m])/ ignoring(state)\nirate(mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=\"scanned_objects\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Index Filtering Effectiveness",
     "type": "graph",
     "description": "Ratio of index entries scanned compared divided by sum of index entries scanned plus whole documents scanned.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects\"}) / ignoring(state)\nsum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects|scanned\"})))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects\"}) / ignoring(state)\nsum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects|scanned\"}))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Index Filtering Effectiveness",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects\"}) / ignoring(state)\nsum by (service_name) (mongodb_mongod_metrics_query_executor_total{service_name=~\"$service_name\", state=~\"scanned_objects|scanned\"})",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Top Opcounters",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 16 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type!=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type!=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type!=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type!=\"command\"}[5m])) + \nsum(rate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongod_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[5m]) or\nrate(mongodb_mongos_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_mongos_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[5m]) or \nrate(mongodb_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[$interval]) or \nirate(mongodb_op_counters_repl_total{service_name=~\"$service_name\", type!~\"(command|query|getmore)\"}[5m])) +\nsum(rate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongod_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[5m]) or\nrate(mongodb_mongos_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongos_metrics_ttl_deleted_documents_total{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top Document Operations",
   "type": "singlestat",
   "description": "Documents inserted, updated, deleted or returned per second.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 16 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Top Queued Operations",
   "type": "singlestat",
   "description": "Operations that are currently queued and waiting for read or write locks",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 16 },
   "format": "ops",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Total Assert Events",
   "type": "singlestat",
   "description": "Asserts. (Not a primary indicator of anything.)",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 16 },
   "format": "ops",
   "valueName": "total",
   "targets": [
    {
     "expr": "sum(rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Opcounters Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Command Operations",
     "type": "graph",
     "description": "The average rate of commands performed per second over the selected sample period",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m])))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Command Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"command\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Getmore Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Getmore Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"getmore\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Delete Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Delete Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"delete\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Insert Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Insert Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"insert\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Update Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Update Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"update\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Query Operations",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m])))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Query Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
     "targets": [
      {
       "expr": "sum by (service_name) (rate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongod_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m]) or \nrate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_mongos_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m]) or \nrate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[$interval]) or \nirate(mongodb_op_counters_total{service_name=~\"$service_name\", type=\"query\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Document Operations Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Document Delete Operations",
     "type": "graph",
     "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"deleted\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"deleted\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Delete Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"deleted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"deleted\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Document Insert Operations",
     "type": "graph",
     "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"inserted\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"inserted\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Insert Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"inserted\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"inserted\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Document Return Operations",
     "type": "graph",
     "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"returned\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"returned\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Return Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"returned\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"returned\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Document Update Operations",
     "type": "graph",
     "description": "This panel shows the actual number of documents that were affected on average during the given time period. A single *update* command for example could perform updates on hundreds or thousands of documents. If these counters seem high, you might want to check your statements to make sure they are properly operating against the documents that they should.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"updated\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"updated\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Document Update Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"updated\"}[$interval]) or \nirate(mongodb_mongod_metrics_document_total{service_name=~\"$service_name\",state=\"updated\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queued Operations Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Queued Read Operations",
     "type": "graph",
     "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"reader\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"reader\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Queued Read Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"reader\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"reader\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Queued Write Operations",
     "type": "graph",
     "description": "This shows the number of read and write operations that are waiting due to for a lock. Consistently small values here should not be of concern, but if the values are consistently high the queries causing long lock times should be tracked down and fixed.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"writer\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"writer\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Queued Write Operations",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "targets": [
      {
       "expr": "avg by (service_name) (max_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"writer\"}[$interval]) or \nmax_over_time(mongodb_mongod_global_lock_current_queue{service_name=~\"$service_name\",type=\"writer\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Assert Events Detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 5 Assert Msg Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Assert Msg Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"msg\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Assert Regular Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": " Assert Regular Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"regular\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Assert Rollovers Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Assert Rollovers Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"rollovers\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Assert User Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Assert User Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"user\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"user\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Top 5 Assert Msg Events",
     "type": "graph",
     "description": "This panel shows the number of assert events per second on average over the given time period. In most cases assertions are trivial, but you would want to check your log files if this counter spikes or is consistently high.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "topk(5,avg by (service_name) ((rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]))))",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "avg(rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]))",
       "legendFormat": "Avg"
      }
     ]
    },
    {
     "title": "Assert Warning Events",
     "type": "grafana-polystat-panel",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "avg by (service_name) (rate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongod_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]) or\nrate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_mongos_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]) or\nrate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[$interval]) or \nirate(mongodb_asserts_total{service_name=~\"$service_name\",type=\"warning\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  }
 ]
}