{
 "title": "MongoDB Cluster Summary",
 "tags": [
  "MongoDB_HA",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(mongodb_up,cluster)"
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": "label_values(mongodb_up{cluster=\"$cluster\"},service_name)"
   },
   {
    "name": "shard",
    "label": "Shard Name",
    "query": "label_values(mongodb_mongos_db_collections_total{cluster=\"$cluster\"},shard)"
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_name)"
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
   },
   {
    "name": "username",
    "label": "Username",
    "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
   },
   { "name": "schema", "label": "Schema" }
  ]
 },
 "panels": [
  {
   "title": " ",
   "type": "digiapulssi-breadcrumb-panel",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Sharded DBs",
   "type": "singlestat",
   "description": "Sharding is a method for distributing data across multiple machines. MongoDB uses sharding to support deployments with very large data sets and high throughput operations.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_databases_total{cluster=\"$cluster\", type=\"partitioned\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Unsharded DBs",
   "type": "singlestat",
   "description": "A MongoDB sharded cluster deployment can contain collections that are either unsharded (the default when created) or sharded.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_databases_total{cluster=\"$cluster\", type=\"unpartitioned\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Amount of Collections in Shards",
   "type": "yesoreyeram-boomtable-panel",
   "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "targets": [
    {
     "expr": "max by (db,shard) (mongodb_mongos_db_collections_total{cluster=\"$cluster\",db!~\"admin|config\"})",
     "legendFormat": "{{db}} | {{shard}} | Collections"
    }
   ]
  },
  {
   "title": "Size of Collections in Shards",
   "type": "yesoreyeram-boomtable-panel",
   "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "expr": "max by (db,shard) (mongodb_mongos_db_data_size_bytes{cluster=\"$cluster\",db!~\"admin|config\"})",
     "legendFormat": "{{db}} | {{shard}} | Collections"
    }
   ]
  },
  {
   "title": "Shards",
   "type": "singlestat",
   "description": "A shard contains a subset of sharded data for a sharded cluster. Together, the cluster’s shards hold the entire data set for the cluster.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_total{cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "singlestat",
   "description": "A chunk consists of a subset of sharded data.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(mongodb_mongos_sharding_chunks_total{cluster=\"$cluster\"})",
     "legendFormat": "Chunks"
    }
   ]
  },
  {
   "title": "Draining Shards",
   "type": "singlestat",
   "description": "When you run removeShard, MongoDB drains the shard by using the balancer to move the shard’s chunks to other shards in the cluster. Once the shard is drained, MongoDB removes the shard from the cluster.",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_shards_draining_total{cluster=\"$cluster\"})",
     "legendFormat": "Draining Total"
    }
   ]
  },
  {
   "title": "Sharded Collections",
   "type": "singlestat",
   "description": "MongoDB stores documents in collections. Collections are analogous to tables in relational databases.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_collections_total{cluster=\"$cluster\"})",
     "legendFormat": "Shards"
    }
   ]
  },
  {
   "title": "Balancer Enabled",
   "type": "singlestat",
   "description": "The MongoDB balancer is a background process that monitors the number of chunks on each shard. ",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max(mongodb_mongos_sharding_balancer_enabled{cluster=\"$cluster\"})",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "Chunks Balanced",
   "type": "singlestat",
   "description": "When the number of chunks on a given shard reaches specific migration thresholds, the balancer attempts to automatically migrate chunks between shards and reach an equal number of chunks per shard.",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "min(mongodb_mongos_sharding_chunks_is_balanced{cluster=\"$cluster\"})",
     "legendFormat": "Cluster Balanced"
    }
   ]
  },
  {
   "title": "QPS of Config Services",
   "type": "grafana-polystat-panel",
   "description": "Config services store the metadata for a sharded cluster. The metadata reflects state and organization for all data and components within the sharded cluster. The metadata includes the list of chunks on every shard and the ranges that define the chunks.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "(sum by (service_name) (rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m])) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{cluster=\"$cluster\",set!~\"$shard\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\",set!~\"$shard\"}))",
     "legendFormat": "{{service_name}}"
    }
   ]
  },
  {
   "title": "QPS of Mongos Service",
   "type": "grafana-polystat-panel",
   "description": "Mongos is a routing service for MongoDB shard configurations that processes queries from the application layer, and determines the location of this data in the sharded cluster, in order to complete these operations. From the perspective of the application, a mongos instance behaves identically to any other MongoDB instance.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "(sum by (service_name) (rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m])) * on (service_name) group_right avg by (service_name) (avg by (service_name) (mongodb_mongos_db_collections_total{cluster=\"$cluster\"}) / avg by (service_name) (mongodb_mongos_db_collections_total{cluster=\"$cluster\"})))",
     "legendFormat": "{{service_name}} "
    }
   ]
  },
  {
   "title": "QPS of Services in Shard - $shard",
   "type": "grafana-polystat-panel",
   "description": "A shard contains a subset of sharded data for a sharded cluster. Together, the cluster’s shards hold the entire data set for the cluster.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 16 },
   "repeat": "shard",
   "targets": [
    {
     "expr": "(sum by (service_name) (rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m])) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{cluster=\"$cluster\",set=~\"$shard\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\",set=~\"$shard\"}))",
     "legendFormat": "{{service_name}} "
    }
   ]
  },
  {
   "title": "QPS of Services in Shard - $shard",
   "type": "grafana-polystat-panel",
   "description": "A shard contains a subset of sharded data for a sharded cluster. Together, the cluster’s shards hold the entire data set for the cluster.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "(sum by (service_name) (rate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[$interval]) or irate(mongodb_op_counters_total{service_name=~\"$service_name\",type!=\"command\"}[5m])) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{cluster=\"$cluster\",set=~\"$shard\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\",set=~\"$shard\"}))",
     "legendFormat": "{{service_name}} "
    }
   ]
  },
  {
   "title": "Chunks in Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunks Balanced",
     "type": "natel-discrete-panel",
     "description": "The MongoDB balancer is a background process that monitors the number of chunks on each shard. When the number of chunks on a given shard reaches specific migration thresholds, the balancer attempts to automatically migrate chunks between shards and reach an equal number of chunks per shard.",
     "gridPos": { "h": 4, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "min(mongodb_mongos_sharding_chunks_is_balanced{cluster=\"$cluster\"})",
       "legendFormat": "$cluster"
      }
     ]
    },
    {
     "title": "Amount of Chunks in Shards",
     "type": "yesoreyeram-boomtable-panel",
     "description": "A chunk consists of a subset of sharded data.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 31 },
     "targets": [
      {
       "expr": "mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\",db!~\"admin|config\"}",
       "legendFormat": "{{shard}} | Chunks"
      }
     ]
    },
    {
     "title": "Dynamic of Chunks",
     "type": "graph",
     "description": "The sharding operation creates the initial chunk(s) to cover the entire range of the shard key values. The number of chunks created depends on the configured chunk size. After the initial chunk creation, the balancer migrates these initial chunks across the shards as appropriate as well as manages the chunk distribution going forward.",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 31 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[$interval]) or irate(mongodb_mongos_sharding_shard_chunks_total{cluster=\"$cluster\"}[5m])",
       "legendFormat": "{{shard}}"
      }
     ]
    },
    {
     "title": "Chunks Split Events",
     "type": "graph",
     "description": "MongoDB splits chunks when they grow beyond the configured chunk size. Both inserts and updates can trigger a chunk split.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\"}[$interval]) or\nirate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*split.*\"}[5m])",
       "legendFormat": "{{event}}"
      }
     ]
    },
    {
     "title": "Chunks Move Events",
     "type": "graph",
     "description": "MongoDB migrates chunks in a sharded cluster to distribute the chunks of a sharded collection evenly among shards. ",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*moveChunk.*\"}[$interval]) or\nirate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*moveChunk.*\"}[5m])",
       "legendFormat": "{{event}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indexes in Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount of Indexes in Shards",
     "type": "yesoreyeram-boomtable-panel",
     "description": "Indexes are special data structures that store a small portion of the collection’s data set in an easy to traverse form. ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "mongodb_mongos_db_indexes_total{cluster=\"$cluster\",db!~\"admin|config\"}",
       "legendFormat": "{{db}} | {{shard}} | Collections"
      }
     ]
    },
    {
     "title": "Dynamic of Indexes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "cps" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongos_db_indexes_total{cluster=\"$cluster\",db!~\"admin|config\"}[$interval]) or irate(mongodb_mongos_db_indexes_total{cluster=\"$cluster\",db!~\"admin|config\"}[5m])",
       "legendFormat": "{{shard}}-{{db}}"
      }
     ]
    },
    {
     "title": "Size of Indexes in Shards",
     "type": "yesoreyeram-boomtable-panel",
     "description": "The index stores the value of a specific field or set of fields, ordered by the value of the field. ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "mongodb_mongos_db_index_size_bytes{cluster=\"$cluster\",db!~\"admin|config\"}",
       "legendFormat": "{{db}} | {{shard}} | Collections"
      }
     ]
    },
    {
     "title": "Dynamic of Indexes Size",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 36 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "rate(mongodb_mongos_db_index_size_bytes{cluster=\"$cluster\",db!~\"admin|config\"}[$interval]) or rate(mongodb_mongos_db_index_size_bytes{cluster=\"$cluster\",db!~\"admin|config\"}[5m])",
       "legendFormat": "{{shard}}-{{db}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Objects in Shards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Amount of Objects in Shards",
     "type": "yesoreyeram-boomtable-panel",
     "description": "Documents in MongoDB are objects stored in a format called BSON, a binary-encoded superset of JSON that supports additional data types.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 29 },
     "targets": [
      {
       "expr": "mongodb_mongos_db_objects_total{cluster=\"$cluster\",db!~\"admin|config\"}",
       "legendFormat": "{{db}} | {{shard}} | Collections"
      }
     ]
    },
    {
     "title": "Dynamic of Objects",
     "type": "graph",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(mongodb_mongos_db_objects_total{cluster=\"$cluster\",db!~\"admin|config\"}[$interval]) or increase(mongodb_mongos_db_objects_total{cluster=\"$cluster\",db!~\"admin|config\"}[5m])",
       "legendFormat": "{{shard}}-{{db}}"
      }
     ]
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Current Connections Per Shard",
   "type": "graph",
   "description": "TCP connections (Incoming) in mongod processes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (set) (avg by (service_name,set) (mongodb_connections{cluster=\"$cluster\", state=\"current\"}) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{cluster=\"$cluster\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\"}))",
     "legendFormat": "{{set}}"
    },
    {
     "expr": "sum by () (avg by (service_name,set) (mongodb_connections{cluster=\"$cluster\", state=\"current\"}) * on (service_name) group_right avg by (service_name,set) (mongodb_mongod_replset_my_state{cluster=\"$cluster\"}/ mongodb_mongod_replset_my_state{cluster=\"$cluster\"}))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "graph",
   "description": "Incoming connections to mongos nodes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (state) (max_over_time(mongodb_connections{cluster=\"$cluster\"}[$interval]) or max_over_time(mongodb_connections{cluster=\"$cluster\"}[5m]))",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Connections Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current Connections ",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name) (max_over_time(mongodb_connections{cluster=\"$cluster\",service_name=~\"$service_name\",state=\"current\"}[$interval]) or \nmax_over_time(mongodb_connections{cluster=\"$cluster\",service_name=~\"$service_name\",state=\"current\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name) (max_over_time(mongodb_connections{cluster=\"$cluster\",service_name=~\"$service_name\",state=\"available\"}[$interval]) or \nmax_over_time(mongodb_connections{cluster=\"$cluster\",service_name=~\"$service_name\",state=\"available\"}[5m]))",
       "legendFormat": "{{service_name}}"
      }
     ]
    }
   ]
  },
  { "title": "Cursors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Cursors Per Shard",
   "type": "graph",
   "description": "The Cursor is a MongoDB Collection of the document which is returned upon the find method execution. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(sum(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"} or mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}) by (service_name) * on (service_name) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    },
    {
     "expr": "sum(sum(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"} or mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}) by (service_name) * on (service_name) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Mongos Cursors",
   "type": "graph",
   "description": "The Cursor is a MongoDB Collection of the document which is returned upon the find method execution.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by () (\nmax_over_time(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[5m]) or max_over_time(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[5m]) or\nmax_over_time(mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}[$interval]) or\nmax_over_time(mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}[5m]) or\nmax_over_time(mongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\"}[$interval]) or\nmax_over_time(mongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\"}[5m])\n)",
     "legendFormat": "Coursors"
    }
   ]
  },
  {
   "title": "Cursors Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mongos Cursors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 49 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (service_name) (\nmax_over_time(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[5m]) or max_over_time(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[5m]) or\nmax_over_time(mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}[$interval]) or\nmax_over_time(mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}[5m]) or\nmax_over_time(mongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\"}[$interval]) or\nmax_over_time(mongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\"}[5m])\n)",
       "legendFormat": "{{service_name}}"
      },
      {
       "expr": "sum by () (\nmax_over_time(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongod_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[5m]) or max_over_time(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[$interval]) or\nmax_over_time(mongodb_mongos_metrics_cursor_open{cluster=\"$cluster\", state=\"total\"}[5m]) or\nmax_over_time(mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}[$interval]) or\nmax_over_time(mongodb_mongod_cursors{cluster=\"$cluster\", state=\"total_open\"}[5m]) or\nmax_over_time(mongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\"}[$interval]) or\nmax_over_time(mongodb_mongos_cursors{cluster=\"$cluster\", state=\"total_open\"}[5m])\n)",
       "legendFormat": "Total"
      }
     ]
    }
   ]
  },
  { "title": "Mongos Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Operations Per Shard",
   "type": "graph",
   "description": "Ops/sec, classified by legacy wire protocol type (query, insert, update, delete, getmore).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(sum(rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\"}[5m])) by (instance) * on (instance) \ngroup_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Total Mongos Operations",
   "type": "graph",
   "description": "Ops/sec, classified by legacy wire protocol type (query, insert, update, delete, getmore).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=~\"$cluster\", type!=\"command\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=~\"$cluster\", type!=\"command\"}[5m]))",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Operations Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "repeat": "service_name",
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 80 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 87 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Operations $service_name",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 87 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum by (type) (rate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[$interval]) or \nirate(mongodb_op_counters_total{cluster=\"$cluster\", type!=\"command\",service_name=~\"$service_name\"}[5m]))",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 59 } },
  {
   "title": "Replication Lag by Set",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max by (set) (max(max_over_time(mongodb_mongod_replset_member_replication_lag{cluster=\"$cluster\"}[$interval]) > 0) by (service_name,set) or max(max_over_time(mongodb_mongod_replset_member_replication_lag{cluster=\"$cluster\"}[5m]) > 0) by (service_name,set))",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Oplog Range by Set",
   "type": "graph",
   "description": "Timespan 'window' between oldest and newest ops in the Oplog collection.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(max(mongodb_mongod_replset_oplog_head_timestamp{cluster=\"$cluster\"}-mongodb_mongod_replset_oplog_tail_timestamp{cluster=\"$cluster\"}) by (service_name) * on (service_name) group_right mongodb_mongod_replset_my_state{cluster=\"$cluster\"} / mongodb_mongod_replset_my_state{cluster=\"$cluster\"}) by (set)",
     "legendFormat": "{{set}}"
    }
   ]
  },
  {
   "title": "Change Log Events",
   "type": "graph",
   "description": "Count, over last 10 minutes, of all types of config db changelog events.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*(shard|Shard).*\"}[$interval]) or\nirate(mongodb_mongos_sharding_changelog_10min_total{cluster=\"$cluster\", event=~\".*(shard|Shard).*\"}[5m])",
     "legendFormat": "{{event}}"
    }
   ]
  }
 ]
}